### ISSUE TITLE
Update "My votes" when txn goes through

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/frontend-v2#1501]
**Describe the bug**
After a vote txn goes through the UI table should auto-refresh to show the user's vote

**To Reproduce**
Vote on a gauge

**Expected behavior**
As soon as the UI detects the txn has been included in a block, "My votes" should reflect the new state

**Screenshots**
![image](https://user-images.githubusercontent.com/34865315/158775564-d06688c7-89f4-425f-8997-736bfc86dc81.png)

**Comment by garethfuller** [comment]
#1492

**Comment by garethfuller** [comment]
@markusbkoch I've handled this by refetching the votes state as soon as the vote modal is closed. The reason I haven't done it on tx success is because it updates the state of the form in the modal and triggers validations again which can lead to error messages if you've used up all your allocation in that vote. There are ways we can prevent this by redesigning the success state a little, but for now I think this solution is sufficient. Let me know if you think otherwise.
