### ISSUE TITLE
On-Chain Token Prices vs CoinGecko When Creating Pools

### ISSUE THREAD

**Issue by chriscrutt** [balancer-labs/frontend-v2#2718]
As it is currently, the Pool Creation page uses the current prices of tokens via CoinGecko (see bottom right)

![image](https://user-images.githubusercontent.com/6835463/215286178-da2d5336-bcec-46af-9013-418f7ab1e611.png)

Now there's nothing wrong with that, but being an on-chain project, it might be good to get on-chain prices. There are a number of ways to do this.

The first would be [ChainLink](https://docs.chain.link/data-feeds/price-feeds/addresses) as they offer free price feeds for various coins on various chains. The only issue here may be that the pricing updates are [different](https://data.chain.link/) per coin, per chain. Ranging from updating the price every minute, to hours, and sometimes a day.

Another is [1inch](https://docs.1inch.io/docs/spot-price-aggregator/examples#multiple-token-to-eth-prices-usage) as they have their Spot Price Aggregator which converts tokens to their current price in ETH.

A third is [UniSwap](https://docs.uniswap.org/contracts/v2/guides/smart-contract-integration/building-an-oracle) which has multiple types of oracles to use for current token pair prices that you can check on the link earlier.

I would say use [Balancer's Oracle](https://docs.balancer.fi/products/oracles) but as the docs say it is depreciated due to multi-coin pools.

Just an idea I though I'd throw out there! Thanks.

**Comment by garethfuller** [comment]
Thanks for posting Chris. This is a fair point but adds some complications that we didn't have the time to think about when we originally implemented the pool creation flow. We could technically use the token prices from our subgraph which is going on the last swap for that token, but if the user is creating a pool with a new token (i.e. there are no other Balancer pools with that token) then this breaks and we'd have to resort to coingecko anyway. As for using other onchain pricing solutions, that may be an option but would require a change in our [SDK where the price fetching actually happens](https://github.com/balancer-labs/balancer-sdk/tree/develop/balancer-js/src/modules/data/token-prices), this would also have implications throughout the app and not just in the pool creation flow. Closing for now because there's nothing actionable we can do right now.
